#!/usr/bin/env bash

set -e
[ -n "$DOTFILES_DEBUG" ] && set -x

# Global vars.
HOME=${HOME}
EXEC_PATH=${PWD}
VUNDLE_PATH="${HOME}/.vim/bundle/Vundle.vim"

# Pre check.
check_essential_softwares()
{
    local essentials=("vim" "git")
    for e in "${essentials[@]}"
    do
        type ${e} 2>&1 > /dev/null
        if [ "$?" -ne 0 ]; then
            echo "ERROR: **${e}** is not installed!"
            exit 1
        fi
        echo "Checking ${e}...ok"
    done
    echo
}

create_softlinks()
{
    local dotfiles=(".pip" ".vimrc" ".gitconfig")
    for dotfile in "${dotfiles[@]}"
    do
        ln -sf "${EXEC_PATH}/${dotfile}" "${HOME}/${dotfile}"
        echo "Create symlink ${HOME}/${dotfile}"
    done
    echo
}

install_plugins_online()
{
    if [ -d "${VUNDLE_PATH}" ]; then
        echo "${VUNDLE_PATH} already exits. Updating..."
        cd "${VUNDLE_PATH}"
        git pull
        cd - > /dev/null 2>&1
    else
        echo "${VUNDLE_PATH} not exists. Downloading..."
        git clone https://github.com/gmarik/Vundle.vim.git ${VUNDLE_PATH}
    fi

    # Install plugins.
    echo "Installing vim plugins..."
    vim +PluginInstall +qall
}

install_plugins_offline()
{
    local dot_vim_path="${HOME}/.vim"
    local bundle_tar="bundle.tar.gz"

    [ ! -d "$dot_vim_path" ] && mkdir ${dot_vim_path}

    if [ -f "${bundle_tar}" ]; then
        echo "Install vundle and plugins offline"

        rm -rf "${dot_vim_path}/bundle"
        cp ${bundle_tar} ${dot_vim_path}
        cd ${dot_vim_path}

        echo "Unpacking ${bundle_tar}..."
        tar zxvf ${bundle_tar} > /dev/null 2>&1
        rm ${bundle_tar}
        cd - > /dev/null 2>&1

        echo "Done!"
    else
        echo "ERROR: **"${bundle_tar}" not exists!"
        exit 1
    fi
}

main()
{
    check_essential_softwares
    create_softlinks
    if [ -n "$1" ] && [ "$1" = "--offline" ]; then
        install_plugins_offline
    else
        install_plugins_online
    fi
}

# Run script.
RUNNING=$(basename $0)
[ "$RUNNING" = "setup-install" ] && main $1

